command:
  name: Send Command
  description: Send a voice command to Plex Voice Cast.
  fields:
    command:
      name: Command
      description: The voice command, e.g. "Play Breaking Bad on the Living Room TV".
      required: true
      example: Play Breaking Bad on the Living Room TV
      selector:
        text:
